version: '3'
services:
  web:
    image: hugo
    volumes:
      - ./site:/site
    working_dir: /site
    ports:
      - "1313:1313"
    command: ["hugo", "server", "--bind", "0.0.0.0"]
    entrypoint: [""]

